### ISSUE TITLE
Question about the MapApi

### ISSUE THREAD

**Issue by ganevbg** [misterokaygo/MapAssist#117]
Hi there, I am pretty sure something is missing, on my machine because it is a fresh install, but i can't figure out where the problem is.I get the the folloing error 
"No connection could be made because the target machine actively refused it 127.0.0.1:8080".  Here is the stack trace:

`at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at MapAssist.Helpers.MapApi.CreateSession(Difficulty difficulty, UInt32 mapSeed) in C:\Users\Admin\Source\Repos\MapAssist\Helpers\MapApi.cs:line 55
   at MapAssist.Helpers.MapApi..ctor(HttpClient client, Difficulty difficulty, UInt32 mapSeed) in C:\Users\Admin\Source\Repos\MapAssist\Helpers\MapApi.cs:line 73
   at MapAssist.Overlay.MapUpdateTimer_Tick(Object sender, EventArgs e) in C:\Users\Admin\Source\Repos\MapAssist\Overlay.cs:line 122
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)`

Any tips would be appreciated :)

**Comment by AudriusButkevicius** [comment]
Support is handled on the discord, not the bug tracker.
